version: "3.4"

services:
  # Backend API Service
  api:
    build: ./BackEnd
    container_name: dotnet_api
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - backend

  # Database Service
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./Opentelemetry/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Monitoring and Observability Services
volumes:
  postgres-data:
  grafana-node-1-data:
  grafana-node-2-data:
  prometheus:
  loki:
  tempo:

networks:
  backend:
    driver: bridge
